{% set name = "kalepy" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kalepy-{{ version }}.tar.gz
  sha256: dcac1fa78db55f88222eac655d6b11cecb63f61b5a37483aff48cb29374a2da8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - six
    - matplotlib-base >=3
    - numba

test:
  imports:
    - kalepy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lzkelley/kalepy/
  summary: Kernel Density Estimation (KDE) and sampling.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
